### PR TITLE
admin: include cilium networkpolicies in envoy config dump

### PR DESCRIPTION
**Pull request by mhofstetter**
Currently, only builtin Envoy resources are part of the Envoy config dump on the admin API (`/admin/config_dump`).

This commit adds Ciliums NetworkPolicies to the config dump, by registering a callback to the configtracker of the adminserver.

This way, the network policies which are actually taken into account by the Envoy Cilium filters are also part of Ciliums sysdump.

Example output (Network Policy output manually flattened to reduce vertical usage)

```
{
    "configs": [
     {
      "@type": "type.googleapis.com/envoy.admin.v3.BootstrapConfigDump",
      ...
     },
     {
      "@type": "type.googleapis.com/envoy.admin.v3.ClustersConfigDump",
      "static_clusters": [
       ...
      ]
     },
     {
      "@type": "type.googleapis.com/envoy.admin.v3.ListenersConfigDump",
      "version_info": "3",
      "dynamic_listeners": [
       ...
      ]
     },
     {
      "@type": "type.googleapis.com/cilium.NetworkPoliciesConfigDump",
      "networkpolicies": [
       {
        "endpoint_ips": ["10.244.1.10"],
        "endpoint_id": "3559",
        "ingress_per_port_policies": [{"port": 80, "rules": [{"http_rules": {"http_rules": [{"headers": [{"name": ":path","string_match": {"safe_regex": {"regex": "/"}}}]}]}}]}],
        "egress_per_port_policies": [{"port": 53}, {"port": 80, "rules": [
            {"remote_policies": ["24471"], "http_rules": {"http_rules": [{"headers": [{"name": ":path","string_match": {"safe_regex": {"regex": "/"}}}]}]}},
            {"remote_policies": ["61667"], "http_rules": {"http_rules": [{"headers": [{"name": ":path","string_match": {"safe_regex": {"regex": "/"}}}]}]}}
          ]}],
        "conntrack_map_name": "global"
       },
       {
        "endpoint_ips": ["10.244.1.132"],
        "endpoint_id": "3962",
        "ingress_per_port_policies": [{}],
        "egress_per_port_policies": [{}],
        "conntrack_map_name": "global"
       },
       ...
      ]
     },
        ...
   }
```

### CODE REVIEW

**Comment by mhofstetter** [comment]
/test-cilium-integration ciliumCli=d3fe1c3d38bc83c1c3dc350f09d95fa2811fdd2a

**Comment by mhofstetter** [comment]
/test-cilium-integration ciliumCli=d3fe1c3d38bc83c1c3dc350f09d95fa2811fdd2a

**Comment by mhofstetter** [comment]
/test-cilium-integration ciliumCli=d3fe1c3d38bc83c1c3dc350f09d95fa2811fdd2a

**Review by jrajahalme — APPROVED** [review]
This is awesome! Wanted for this for the longest time, but never got to dig out how to do this, thank you :-)

**Pull request merged**
