### PR TITLE
build_config: Enable wasm and rate limit extensions

### PR DESCRIPTION
**Pull request by jrajahalme**

### CODE REVIEW

**Comment by mhofstetter** [comment]
@jrajahalme Out of curiosity: Are there specific use-cases / requests why these extensions should become enabled?

**Review by mhofstetter — APPROVED** [review]

**Comment by jrajahalme** [comment]
Let's hold off on merging this until we have branched off for the imminent Cilium 1.14 release.

**Comment by sayboras** [comment]
v1.25 branch is cut, so whenever you are comfortable pressing the green button :heavy_check_mark:

**Review by sayboras — APPROVED** [review]
LGTM :heavy_check_mark:

**Pull request merged**
